spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/crm?useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

management.security.enabled=false
management.context-path=/appinfo

spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false
